//! Differential correctness against the benchmark fixtures, when they exist.
//!
//! `bench/fixtures` is gitignored and regenerated by `scripts/make-fixtures.sh`.
//! These tests skip themselves when a fixture is absent so a fresh checkout
//! still has a green suite; on a bench machine they are the large-input half of
//! the differential check, decoding in deliberately awkward chunk sizes and
//! comparing length and CRC32 against `xz -dc`.

mod common;

use std::process::{Command, Stdio};

use common::*;

fn crc32(buf: &[u8], seed: u32) -> u32 {
    // Bitwise IEEE CRC32; slow, but it runs once per fixture on the test's own
    // output and keeps the crate's dev-dependency list empty.
    let mut crc = !seed;
    for &b in buf {
        crc ^= u32::from(b);
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                0xEDB8_8320 ^ (crc >> 1)
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// Runs `xz -dc` on the fixture and returns its output length and CRC32,
/// without ever holding the whole gigabyte in memory.
fn oracle(args: &[&str]) -> Option<(u64, u32)> {
    let mut child = Command::new("xz")
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdout = child.stdout.take()?;
    let mut buf = vec![0u8; 1 << 20];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        use std::io::Read;
        let n = stdout.read(&mut buf).ok()?;
        if n == 0 {
            break;
        }
        len += n as u64;
        crc = crc32(&buf[..n], crc);
    }
    child.wait().ok()?.success().then_some((len, crc))
}

/// Streams the fixture through the decoder in `in_chunk`-sized input slices
/// and `out_chunk`-sized output slices, returning length and CRC32.
fn ours_lzma1(data: &[u8], in_chunk: usize, out_chunk: usize) -> (u64, u32) {
    use lzma_fast::{FinishMode, LzmaAloneHeader, LzmaDecoder, Status};
    let header: [u8; 13] = data[..13].try_into().unwrap();
    let props = LzmaAloneHeader::parse(&header).unwrap().props;
    let mut dec = LzmaDecoder::new(props).unwrap();
    let mut input = &data[13..];
    let mut out = vec![0u8; out_chunk];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        let feed = in_chunk.min(input.len());
        let p = dec
            .decode(&input[..feed], &mut out, FinishMode::Any)
            .expect("fixture decodes");
        input = &input[p.read..];
        len += p.written as u64;
        crc = crc32(&out[..p.written], crc);
        if p.status == Status::FinishedWithMark || (p.read == 0 && p.written == 0) {
            break;
        }
    }
    (len, crc)
}

fn ours_lzma2(dict_prop: u8, payload: &[u8], in_chunk: usize, out_chunk: usize) -> (u64, u32) {
    use lzma_fast::{FinishMode, Lzma2Decoder, Status};
    let mut dec = Lzma2Decoder::new(dict_prop).unwrap();
    let mut input = payload;
    let mut out = vec![0u8; out_chunk];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        let feed = in_chunk.min(input.len());
        let p = dec
            .decode(&input[..feed], &mut out, FinishMode::Any)
            .expect("fixture decodes");
        input = &input[p.read..];
        len += p.written as u64;
        crc = crc32(&out[..p.written], crc);
        if p.status == Status::FinishedWithMark || (p.read == 0 && p.written == 0) {
            break;
        }
    }
    (len, crc)
}

/// Odd sizes on purpose: 1 and 7 keep the decoder in the `tempBuf` path, 4096
/// straddles symbol boundaries arbitrarily, 1 MiB is the shape a real caller
/// uses.
const CHUNKS: &[(usize, usize)] = &[(1, 4096), (7, 1), (4096, 4096), (1 << 20, 1 << 20)];

#[test]
fn lzma1_fixtures_match_xz() {
    for name in ["p256.bin.lzma", "payload.bin.lzma"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run scripts/make-fixtures.sh)");
            continue;
        };
        let Some(expected) = oracle(&["-dc", "-T1", "--format=lzma", path.to_str().unwrap()])
        else {
            eprintln!("skipping {name}: xz oracle unavailable");
            continue;
        };
        // The 1-byte-at-a-time lanes are quadratic in a gigabyte; run the
        // awkward chunk sizes on the smaller fixture only.
        let chunks: &[(usize, usize)] = if data.len() > (1 << 29) {
            &[(1 << 20, 1 << 20)]
        } else {
            CHUNKS
        };
        for &(in_chunk, out_chunk) in chunks {
            let got = ours_lzma1(&data, in_chunk, out_chunk);
            assert_eq!(got, expected, "{name} ({in_chunk},{out_chunk})");
        }
    }
}

#[test]
fn lzma2_fixtures_match_xz() {
    let name = "p256.bin.xz";
    let path = repo_root().join("bench/fixtures").join(name);
    let Ok(data) = std::fs::read(&path) else {
        eprintln!("skipping {name}: fixture absent (run scripts/make-fixtures.sh)");
        return;
    };
    let Some(expected) = oracle(&["-dc", "-T1", path.to_str().unwrap()]) else {
        eprintln!("skipping {name}: xz oracle unavailable");
        return;
    };
    let (dict_prop, payload) = xz_lzma2_block(&data).expect("single LZMA2 block");
    for &(in_chunk, out_chunk) in CHUNKS {
        let got = ours_lzma2(dict_prop, payload, in_chunk, out_chunk);
        assert_eq!(got, expected, "{name} ({in_chunk},{out_chunk})");
    }
}

/// The `.7z` fixtures are single-file, single-folder archives, so the LZMA2
/// pack stream is one byte range and the dictionary property byte is in the
/// coder properties. Nothing here parses a real 7z; see the helper's own
/// module docs.
#[test]
fn the_seven_z_fixtures_are_one_lzma2_pack_stream() {
    for name in ["mt.7z", "st.7z"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run scripts/make-fixtures.sh)");
            continue;
        };
        let ps = sevenz::pack_stream(&data)
            .unwrap_or_else(|| panic!("{name}: not a single-folder LZMA2 archive"));
        // 32 is the size of the signature header, which is where a 7z archive
        // written in one pass puts the first pack stream.
        assert_eq!(ps.offset, 32, "{name}");
        assert_eq!(ps.unpacked_len, 1 << 30, "{name}");
        assert_eq!(ps.dict_prop, 26, "{name}");
        assert!(ps.offset + ps.packed_len <= data.len() as u64, "{name}");
    }
}

/// Runs a command that writes the decoded bytes to stdout and returns the
/// length and CRC32 of what came out.
#[cfg(feature = "std")]
fn stdout_oracle(prog: &str, args: &[&str]) -> Option<(u64, u32)> {
    let mut child = Command::new(prog)
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdout = child.stdout.take()?;
    let mut buf = vec![0u8; 1 << 20];
    let (mut len, mut crc) = (0u64, 0u32);
    loop {
        use std::io::Read;
        let n = stdout.read(&mut buf).ok()?;
        if n == 0 {
            break;
        }
        len += n as u64;
        crc = crc32(&buf[..n], crc);
    }
    child.wait().ok()?.success().then_some((len, crc))
}

/// The gigabyte fixtures through the parallel decoder, at several thread
/// counts, against both this crate's single-threaded path and 7-Zip itself.
///
/// `mt.7z` was written with `-mmt=on` and so has many independently decodable
/// runs; `st.7z` was written with `-mmt=1` and has exactly one, which is the
/// case the parallel decoder has to fall back to single-threaded without
/// buffering the stream.
#[cfg(feature = "std")]
#[test]
fn lzma2_mt_fixtures_match_the_single_threaded_path() {
    use lzma_fast::{Lzma2MtOptions, Lzma2ParallelDecoder};

    let all = std::thread::available_parallelism().map_or(1, std::num::NonZero::get);
    for name in ["mt.7z", "st.7z"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run scripts/make-fixtures.sh)");
            continue;
        };
        let ps = sevenz::pack_stream(&data).expect("single-folder LZMA2 archive");
        let payload = &data[ps.offset as usize..(ps.offset + ps.packed_len) as usize];

        let expected = ours_lzma2(ps.dict_prop, payload, 1 << 20, 1 << 20);
        assert_eq!(expected.0, ps.unpacked_len, "{name}: declared size");

        // The full 1/2/3/8/16 sweep is the small-vector differential test's
        // job; at a gigabyte a run each, three points are enough to show the
        // large-input path agrees.
        for threads in [1, 2, all] {
            let opts = Lzma2MtOptions {
                threads,
                memory_limit: u64::MAX,
            };
            let dec = Lzma2ParallelDecoder::new(ps.dict_prop, &opts).unwrap();
            let mut sink = CrcSink::default();
            let n = dec.decode(payload, &mut sink).expect("fixture decodes");
            assert_eq!((n, sink.crc), expected, "{name} at {threads} threads");
        }

        match stdout_oracle("7zz", &["x", "-so", path.to_str().unwrap()]) {
            Some(o) => assert_eq!(o, expected, "{name}: 7zz disagrees"),
            None => eprintln!("skipping the 7zz oracle for {name}: unavailable"),
        }
    }
}

/// A [`std::io::Write`] that keeps only the length and CRC32, so a gigabyte of
/// output never has to be resident.
#[cfg(feature = "std")]
#[derive(Default)]
struct CrcSink {
    crc: u32,
}

#[cfg(feature = "std")]
impl std::io::Write for CrcSink {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.crc = crc32(buf, self.crc);
        Ok(buf.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}
