//! Differential correctness against the benchmark fixtures, when they exist.
//!
//! `bench/fixtures` is gitignored and regenerated by `scripts/make-fixtures.sh`.
//! These tests skip themselves when a fixture is absent so a fresh checkout
//! still has a green suite; on a bench machine they are the large-input half of
//! the differential check, decoding in deliberately awkward chunk sizes and
//! comparing length and CRC32 against `xz -dc`.

mod common;

use std::process::{Command, Stdio};

use common::*;

fn crc32(buf: &[u8], seed: u32) -> u32 {
    // Bitwise IEEE CRC32; slow, but it runs once per fixture on the test's own
    // output and keeps the crate's dev-dependency list empty.
    let mut crc = !seed;
    for &b in buf {
        crc ^= u32::from(b);
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                0xEDB8_8320 ^ (crc >> 1)
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// Runs `xz -dc` on the fixture and returns its output length and CRC32,
/// without ever holding the whole gigabyte in memory.
fn oracle(args: &[&str]) -> Option<(u64, u32)> {
    let mut child = Command::new("xz")
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdout = child.stdout.take()?;
    let mut buf = vec![0u8; 1 << 20];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        use std::io::Read;
        let n = stdout.read(&mut buf).ok()?;
        if n == 0 {
            break;
        }
        len += n as u64;
        crc = crc32(&buf[..n], crc);
    }
    child.wait().ok()?.success().then_some((len, crc))
}

/// Streams the fixture through the decoder in `in_chunk`-sized input slices
/// and `out_chunk`-sized output slices, returning length and CRC32.
fn ours_lzma1(data: &[u8], in_chunk: usize, out_chunk: usize) -> (u64, u32) {
    use lzma_fast::{FinishMode, LzmaAloneHeader, LzmaDecoder, Status};
    let header: [u8; 13] = data[..13].try_into().unwrap();
    let props = LzmaAloneHeader::parse(&header).unwrap().props;
    let mut dec = LzmaDecoder::new(props).unwrap();
    let mut input = &data[13..];
    let mut out = vec![0u8; out_chunk];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        let feed = in_chunk.min(input.len());
        let p = dec
            .decode(&input[..feed], &mut out, FinishMode::Any)
            .expect("fixture decodes");
        input = &input[p.read..];
        len += p.written as u64;
        crc = crc32(&out[..p.written], crc);
        if p.status == Status::FinishedWithMark || (p.read == 0 && p.written == 0) {
            break;
        }
    }
    (len, crc)
}

fn ours_lzma2(dict_prop: u8, payload: &[u8], in_chunk: usize, out_chunk: usize) -> (u64, u32) {
    use lzma_fast::{FinishMode, Lzma2Decoder, Status};
    let mut dec = Lzma2Decoder::new(dict_prop).unwrap();
    let mut input = payload;
    let mut out = vec![0u8; out_chunk];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        let feed = in_chunk.min(input.len());
        let p = dec
            .decode(&input[..feed], &mut out, FinishMode::Any)
            .expect("fixture decodes");
        input = &input[p.read..];
        len += p.written as u64;
        crc = crc32(&out[..p.written], crc);
        if p.status == Status::FinishedWithMark || (p.read == 0 && p.written == 0) {
            break;
        }
    }
    (len, crc)
}

/// Odd sizes on purpose: 1 and 7 keep the decoder in the `tempBuf` path, 4096
/// straddles symbol boundaries arbitrarily, 1 MiB is the shape a real caller
/// uses.
const CHUNKS: &[(usize, usize)] = &[(1, 4096), (7, 1), (4096, 4096), (1 << 20, 1 << 20)];

#[test]
fn lzma1_fixtures_match_xz() {
    for name in ["p256.bin.lzma", "payload.bin.lzma"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run scripts/make-fixtures.sh)");
            continue;
        };
        let Some(expected) = oracle(&["-dc", "-T1", "--format=lzma", path.to_str().unwrap()])
        else {
            eprintln!("skipping {name}: xz oracle unavailable");
            continue;
        };
        // The 1-byte-at-a-time lanes are quadratic in a gigabyte; run the
        // awkward chunk sizes on the smaller fixture only.
        let chunks: &[(usize, usize)] = if data.len() > (1 << 29) {
            &[(1 << 20, 1 << 20)]
        } else {
            CHUNKS
        };
        for &(in_chunk, out_chunk) in chunks {
            let got = ours_lzma1(&data, in_chunk, out_chunk);
            assert_eq!(got, expected, "{name} ({in_chunk},{out_chunk})");
        }
    }
}

#[test]
fn lzma2_fixtures_match_xz() {
    let name = "p256.bin.xz";
    let path = repo_root().join("bench/fixtures").join(name);
    let Ok(data) = std::fs::read(&path) else {
        eprintln!("skipping {name}: fixture absent (run scripts/make-fixtures.sh)");
        return;
    };
    let Some(expected) = oracle(&["-dc", "-T1", path.to_str().unwrap()]) else {
        eprintln!("skipping {name}: xz oracle unavailable");
        return;
    };
    let (dict_prop, payload) = xz_lzma2_block(&data).expect("single LZMA2 block");
    for &(in_chunk, out_chunk) in CHUNKS {
        let got = ours_lzma2(dict_prop, payload, in_chunk, out_chunk);
        assert_eq!(got, expected, "{name} ({in_chunk},{out_chunk})");
    }
}
